[project]
name = "bondspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lukasmki", email = "lukasarus@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ase>=3.28.0",
    "pyscf>=2.13.0",
]

[project.scripts]
bondspace = "bondspace:main"

[project.optional-dependencies]
cuda12 = [
    "cutensor-cu12>=2.6.0",
    "gpu4pyscf-cuda12x>=1.7.1",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
